### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by einsmein** [einsmein/rhok-station#7]
# Data pipeline
## Financial: Visma Economics
- [ ] Consolidate code that pull data from the API
- [ ] Verify data schema
- [ ] Set up scheduled pulling

## Visit: CSV
- [x] Authentication / authorization for CSV upload?
- [ ] Overwrite existing rows or manually choose rows to upload?
- [ ] Allow admin to manually edit data?

## Members: JoinIt
- [ ] Go over their API again
- [ ] Write code that pull data from the API
- [ ] Verify data schema
- [ ] Set up scheduled pulling

# Ops
- [ ] Decide on and implement monitoring components
    - Simple: Portainer for status of containers
    - Full-blown: Grafana, Loki, Prometheus exporter, Custom prometheus metrics for scheduling worker health
    - Monitor Celery tasks
- [ ] Setup TLS
